name = "yfm_api-dev"
type = "webpack"
route = "api-dev.youfoundme.io/*"
zone_id = "fcf76574bd8c4e042cf94c724cb932c5"
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-08"
account_id = "fd148ae4e7fb02763416f2bca9bb4bdf"
kv_namespaces = [ 
	 { binding = "KV_TOKEN", id = "4e351a432c1240d382fc888ff48e7a8e" }
]


[vars]
ENVIRONMENT = "dev"


[env.prod]
name = "yfm_api"
route = "api.youfoundme.io/*"
kv_namespaces = [ 
	 { binding = "KV_TOKEN", id = "aa9295fd5f2342c7a6423a29282a5864" }
]
[env.prod.vars]
ENVIRONMENT = "prod"
